openapi: 3.0.3
info:
  title: Invoice Service API
  version: 2.0.0
  description: Complete CRUD API for managing invoices, items, and generating PDFs.
paths:
  /invoices:
    get:
      summary: Get all invoices
      description: Retrieve all invoices in the system.
      responses:
        '200':
          description: List of invoices.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/InvoiceDTO'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    post:
      summary: Create new invoice
      description: Create a new invoice with items.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateInvoiceRequest'
      responses:
        '201':
          description: Invoice created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvoiceDTO'
        '400':
          description: Invalid input.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /invoices/{id}:
    get:
      summary: Get invoice by ID
      description: Retrieve invoice details along with its items.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          example: 1
      responses:
        '200':
          description: Invoice found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvoiceDTO'
        '404':
          description: Invoice not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
      summary: Update invoice
      description: Update an existing invoice.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateInvoiceRequest'
      responses:
        '200':
          description: Invoice updated successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvoiceDTO'
        '400':
          description: Invalid input.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Invoice not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      summary: Delete invoice
      description: Delete an existing invoice (cannot delete paid invoices).
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          example: 1
      responses:
        '204':
          description: Invoice deleted successfully.
        '400':
          description: Cannot delete (e.g., invoice is paid).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Invoice not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /invoices/generate-pdf:
    post:
      summary: Generate PDF
      description: Generate a PDF based on provided invoice configuration.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InvoiceConfigDTO'
            example:
              invoiceNumber: "2025-001"
              baseAmount: 1000.00
              irpfPercentage: 15.00
              rePercentage: 5.00
              totalAmount: 1210.00
              color: "#FFFFFF"
              textStyle: "bold"
      responses:
        '200':
          description: PDF generated successfully.
          content:
            application/pdf:
              schema:
                type: string
                format: binary
        '400':
          description: Invalid input.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    CreateInvoiceRequest:
      type: object
      properties:
        companyId:
          type: integer
          example: 1
        clientId:
          type: integer
          example: 1
        invoiceNumber:
          type: string
          example: "2025-001"
        irpfPercentage:
          type: number
          format: float
          example: 15.00
        rePercentage:
          type: number
          format: float
          example: 5.00
        notes:
          type: string
          example: "Factura de servicios profesionales"
        items:
          type: array
          items:
            $ref: '#/components/schemas/CreateInvoiceItemRequest'
      required:
        - companyId
        - clientId
        - invoiceNumber
        - items
    CreateInvoiceItemRequest:
      type: object
      properties:
        description:
          type: string
          example: "Consultoría de software"
        units:
          type: integer
          example: 10
        price:
          type: number
          format: float
          example: 100.00
        vatPercentage:
          type: number
          format: float
          example: 21.00
        discountPercentage:
          type: number
          format: float
          example: 0.00
      required:
        - description
        - units
        - price
        - vatPercentage
    UpdateInvoiceRequest:
      type: object
      properties:
        notes:
          type: string
          example: "Factura actualizada"
        items:
          type: array
          items:
            $ref: '#/components/schemas/CreateInvoiceItemRequest'
    CompanyDTO:
      type: object
      properties:
        id:
          type: integer
          example: 1
        businessName:
          type: string
          example: "TRANSOLIDO S.L."
        taxId:
          type: string
          example: "B91923755"
        address:
          type: string
          example: "Castillo Lastrucci, 3, 3D"
        city:
          type: string
          example: "DOS HERMANAS"
        postalCode:
          type: string
          example: "41701"
        province:
          type: string
          example: "SEVILLA"
        phone:
          type: string
          example: "659889201"
        email:
          type: string
          example: "contacto@transolido.es"
        iban:
          type: string
          example: "ES60 0182 4840 0022 0165 7539"
      required:
        - id
        - businessName
        - taxId
    ClientDTO:
      type: object
      properties:
        id:
          type: integer
          example: 1
        businessName:
          type: string
          example: "SERSFRITRUCKS, S.A."
        taxId:
          type: string
          example: "A50008588"
        address:
          type: string
          example: "JIMÉNEZ DE LA ESPADA, 57, BAJO"
        city:
          type: string
          example: "CARTAGENA"
        postalCode:
          type: string
          example: "30203"
        province:
          type: string
          example: "MURCIA"
        phone:
          type: string
          example: "968123456"
        email:
          type: string
          example: "info@sersfritrucks.com"
      required:
        - id
        - businessName
        - taxId
    InvoiceDTO:
      type: object
      properties:
        id:
          type: integer
          example: 1
        companyId:
          type: integer
          example: 1
        clientId:
          type: integer
          example: 1
        company:
          $ref: '#/components/schemas/CompanyDTO'
        client:
          $ref: '#/components/schemas/ClientDTO'
        invoiceNumber:
          type: string
          example: "2025-001"
        issueDate:
          type: string
          format: date-time
          example: "2025-03-14T10:00:00Z"
        baseAmount:
          type: number
          format: float
          example: 1000.00
        irpfPercentage:
          type: number
          format: float
          example: 15.00
        irpfAmount:
          type: number
          format: float
          example: 150.00
        rePercentage:
          type: number
          format: float
          example: 5.00
        reAmount:
          type: number
          format: float
          example: 50.00
        totalAmount:
          type: number
          format: float
          example: 1210.00
        status:
          type: string
          example: "Pendiente"
        notes:
          type: string
          example: "Factura generada automáticamente."
        createdAt:
          type: string
          format: date-time
          example: "2025-03-14T10:00:00Z"
        updatedAt:
          type: string
          format: date-time
          example: "2025-03-14T10:00:00Z"
        items:
          type: array
          items:
            $ref: '#/components/schemas/InvoiceItemDTO'
      required:
        - id
        - companyId
        - clientId
        - invoiceNumber
        - issueDate
        - baseAmount
        - totalAmount
        - status
        - createdAt
        - updatedAt
    InvoiceItemDTO:
      type: object
      properties:
        id:
          type: integer
          example: 1
        invoiceId:
          type: integer
          example: 1
        description:
          type: string
          example: "Consultoría"
        units:
          type: integer
          example: 2
        discountPercentage:
          type: number
          format: float
          example: 0.00
        price:
          type: number
          format: float
          example: 500.00
        vatPercentage:
          type: number
          format: float
          example: 21.00
        subtotal:
          type: number
          format: float
          example: 1000.00
        total:
          type: number
          format: float
          example: 1210.00
        createdAt:
          type: string
          format: date-time
          example: "2025-03-14T10:00:00Z"
        updatedAt:
          type: string
          format: date-time
          example: "2025-03-14T10:00:00Z"
      required:
        - id
        - invoiceId
        - description
        - units
        - price
        - vatPercentage
        - subtotal
        - total
        - createdAt
        - updatedAt
    InvoiceConfigDTO:
      type: object
      properties:
        invoiceNumber:
          type: string
          example: "2025-001"
        baseAmount:
          type: number
          format: float
          example: 1000.00
        irpfPercentage:
          type: number
          format: float
          example: 15.00
        rePercentage:
          type: number
          format: float
          example: 5.00
        totalAmount:
          type: number
          format: float
          example: 1210.00
        color:
          type: string
          example: "#FFFFFF"
        textStyle:
          type: string
          example: "bold"
      required:
        - invoiceNumber
        - baseAmount
        - totalAmount
    ErrorResponse:
      type: object
      properties:
        code:
          type: integer
          example: 404
        message:
          type: string
          example: "Invoice not found"
      required:
        - code
        - message
