openapi: 3.0.3
info:
  title: Invoice Service API
  version: 1.0.0
  description: API for managing invoices, items, and generating PDFs.
paths:
  /invoices/{id}:
    get:
      summary: Get invoice by ID
      description: Retrieve invoice details along with its items for preview.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          example: 1
      responses:
        '200':
          description: Invoice found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvoiceDTO'
        '404':
          description: Invoice not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /invoices/generate-pdf:
    post:
      summary: Generate PDF
      description: Generate a PDF based on provided invoice configuration.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InvoiceConfigDTO'
            example:
              invoiceNumber: "2025-001"
              baseAmount: 1000.00
              irpfPercentage: 15.00
              rePercentage: 5.00
              totalAmount: 1210.00
              color: "#FFFFFF"
              textStyle: "bold"
      responses:
        '200':
          description: PDF generated successfully.
          content:
            application/pdf:
              schema:
                type: string
                format: binary
        '400':
          description: Invalid input.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    InvoiceDTO:
      type: object
      properties:
        id:
          type: integer
          example: 1
        userId:
          type: integer
          example: 1
        clientId:
          type: integer
          example: 1
        invoiceNumber:
          type: string
          example: "2025-001"
        issueDate:
          type: string
          format: date-time
          example: "2025-03-14T10:00:00Z"
        baseAmount:
          type: number
          format: float
          example: 1000.00
        irpfPercentage:
          type: number
          format: float
          example: 15.00
        irpfAmount:
          type: number
          format: float
          example: 150.00
        rePercentage:
          type: number
          format: float
          example: 5.00
        reAmount:
          type: number
          format: float
          example: 50.00
        totalAmount:
          type: number
          format: float
          example: 1210.00
        status:
          type: string
          example: "Pendiente"
        notes:
          type: string
          example: "Factura generada automáticamente."
        createdAt:
          type: string
          format: date-time
          example: "2025-03-14T10:00:00Z"
        updatedAt:
          type: string
          format: date-time
          example: "2025-03-14T10:00:00Z"
        items:
          type: array
          items:
            $ref: '#/components/schemas/InvoiceItemDTO'
      required:
        - id
        - userId
        - clientId
        - invoiceNumber
        - issueDate
        - baseAmount
        - totalAmount
        - status
        - createdAt
        - updatedAt
    InvoiceItemDTO:
      type: object
      properties:
        id:
          type: integer
          example: 1
        invoiceId:
          type: integer
          example: 1
        description:
          type: string
          example: "Consultoría"
        units:
          type: integer
          example: 2
        discountPercentage:
          type: number
          format: float
          example: 0.00
        price:
          type: number
          format: float
          example: 500.00
        vatPercentage:
          type: number
          format: float
          example: 21.00
        subtotal:
          type: number
          format: float
          example: 1000.00
        total:
          type: number
          format: float
          example: 1210.00
        createdAt:
          type: string
          format: date-time
          example: "2025-03-14T10:00:00Z"
        updatedAt:
          type: string
          format: date-time
          example: "2025-03-14T10:00:00Z"
      required:
        - id
        - invoiceId
        - description
        - units
        - price
        - vatPercentage
        - subtotal
        - total
        - createdAt
        - updatedAt
    InvoiceConfigDTO:
      type: object
      properties:
        invoiceNumber:
          type: string
          example: "2025-001"
        baseAmount:
          type: number
          format: float
          example: 1000.00
        irpfPercentage:
          type: number
          format: float
          example: 15.00
        rePercentage:
          type: number
          format: float
          example: 5.00
        totalAmount:
          type: number
          format: float
          example: 1210.00
        color:
          type: string
          example: "#FFFFFF"
        textStyle:
          type: string
          example: "bold"
      required:
        - invoiceNumber
        - baseAmount
        - totalAmount
    ErrorResponse:
      type: object
      properties:
        code:
          type: integer
          example: 404
        message:
          type: string
          example: "Invoice not found"
      required:
        - code
        - message
