package com.invoices.invoice.presentation.controllers;

import com.invoices.invoice.domain.entities.Invoice;
import com.invoices.invoice.domain.ports.InvoiceRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.redis.core.RedisTemplate;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.net.URI;
import java.util.HashMap;
import java.util.Map;

/**
 * Controller for enhanced PDF generation with VeriFactu verification
 */
@RestController
@RequestMapping("/api/invoices")
@RequiredArgsConstructor
@Slf4j
public class InvoicePdfController {

    private final InvoiceRepository invoiceRepository;
    private final RedisTemplate<String, Object> redisTemplate;

    /**
     * POST /api/invoices/{id}/generate-pdf - Enhanced PDF generation
     * 
     * Generates draft PDF immediately and enqueues VeriFactu verification
     * Returns 202 Accepted with Location header to draft PDF
     * 
     * @param id Invoice ID
     * @return 202 Accepted with Location header
     */
    @PostMapping("/{id}/generate-pdf")
    public ResponseEntity<Map<String, Object>> generatePdfWithVerification(@PathVariable Long id) {
        log.info("[PDF Generation] Starting enhanced PDF generation for invoice {}", id);

        Invoice invoice = invoiceRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("Invoice not found: " + id));

        // Generate draft PDF URL (frontend will generate the actual PDF)
        String draftPdfUrl = String.format("/api/invoices/%d/pdf", id);

        // Enqueue VeriFactu verification automatically
        try {
            Map<String, Object> event = new HashMap<>();
            event.put("invoiceId", id);
            event.put("eventType", "INVOICE_CREATED");
            event.put("autoGenerated", true);
            event.put("timestamp", System.currentTimeMillis());

            redisTemplate.opsForStream().add("verifactu-queue", event);
            log.info("[PDF Generation] Enqueued VeriFactu verification for invoice {}", id);
        } catch (Exception e) {
            log.error("[PDF Generation] Error enqueueing verification for invoice {}: {}",
                    id, e.getMessage());
        }

        // Return 202 Accepted with draft PDF URL
        Map<String, Object> response = new HashMap<>();
        response.put("message", "PDF generation initiated");
        response.put("draftPdfUrl", draftPdfUrl);
        response.put("invoiceId", id);
        response.put("verifactuStatus", invoice.getVerifactuStatus());
        response.put("pdfIsFinal", false);

        return ResponseEntity
                .accepted()
                .location(URI.create(draftPdfUrl))
                .body(response);
    }
}
