openapi: 3.0.3
info:
  title: Document Service API
  version: 1.0.0
  description: API for managing PDF documents stored in MinIO.
paths:
  /documents:
    post:
      summary: Upload a PDF
      description: Upload and store a PDF in MinIO, associating it with an invoice.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                invoiceId:
                  type: integer
                  example: 1
                file:
                  type: string
                  format: binary
              required:
                - invoiceId
                - file
      responses:
        '201':
          description: PDF uploaded successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentDTO'
        '400':
          description: Invalid file format or missing invoiceId.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /documents/{id}:
    get:
      summary: Get a PDF by ID
      description: Retrieve a PDF from MinIO.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          example: 1
      responses:
        '200':
          description: PDF retrieved successfully.
          content:
            application/pdf:
              schema:
                type: string
                format: binary
        '404':
          description: Document not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    DocumentDTO:
      type: object
      properties:
        id:
          type: integer
          example: 1
        invoiceId:
          type: integer
          example: 1
        filePath:
          type: string
          example: "/storage/invoices/2025-001.pdf"
        fileType:
          type: string
          example: "PDF"
        fileName:
          type: string
          example: "Factura_2025-001.pdf"
        uploadedAt:
          type: string
          format: date-time
          example: "2025-03-14T10:35:00Z"
      required:
        - id
        - invoiceId
        - filePath
        - uploadedAt
    ErrorResponse:
      type: object
      properties:
        code:
          type: integer
          example: 404
        message:
          type: string
          example: "Document not found"
      required:
        - code
        - message
