ALTER TABLE companies ADD COLUMN IF NOT EXISTS last_hash VARCHAR(128);
ALTER TABLE companies ADD COLUMN IF NOT EXISTS cert_ref VARCHAR(255);
ALTER TABLE companies ADD COLUMN IF NOT EXISTS cert_password VARCHAR(255);
