openapi: 3.0.3
info:
  title: User Service API
  version: 1.0.0
  description: API for managing users (emitters) and clients.
paths:
  /users/{id}:
    get:
      summary: Get user by ID
      description: Retrieve user (emitter) details.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          example: 1
      responses:
        '200':
          description: User found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDTO'
        '404':
          description: User not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /users/clients/{id}:
    get:
      summary: Get client by ID
      description: Retrieve client details.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          example: 1
      responses:
        '200':
          description: Client found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientDTO'
        '404':
          description: Client not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    UserDTO:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: "José Pérez"
        cif:
          type: string
          example: "A12345678"
        address:
          type: string
          example: "Calle Principal 123, Madrid"
        phone:
          type: string
          example: "912345678"
        email:
          type: string
          example: "jose.perez@transolido.com"
      required:
        - id
        - name
        - cif
        - email
    ClientDTO:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: "Empresa XYZ"
        cif:
          type: string
          example: "B87654321"
        address:
          type: string
          example: "Avenida Secundaria 456, Barcelona"
        phone:
          type: string
          example: "934567890"
        email:
          type: string
          example: "contacto@empresaxyz.com"
      required:
        - id
        - name
        - cif
        - email
    ErrorResponse:
      type: object
      properties:
        code:
          type: integer
          example: 404
        message:
          type: string
          example: "User/Client not found"
      required:
        - code
        - message
