package com.invoices.invoice.domain.usecases;

import com.invoices.invoice.domain.entities.Client;
import com.invoices.invoice.domain.ports.ClientEventPublisher;
import com.invoices.invoice.domain.ports.ClientRepository;
import com.invoices.invoice.domain.ports.CompanyRepository;
import com.invoices.shared.domain.exception.ResourceNotFoundException;
import lombok.extern.slf4j.Slf4j;

/**
 * UseCase for creating a new client.
 *
 * Encapsulates business logic for client creation including:
 * - Company validation
 * - Client data validation
 * - Client persistence
 * - Event publishing
 */
@Slf4j
public class CreateClientUseCase {

    private final ClientRepository clientRepository;
    private final CompanyRepository companyRepository;
    private final ClientEventPublisher eventPublisher;

    public CreateClientUseCase(
            ClientRepository clientRepository,
            CompanyRepository companyRepository,
            ClientEventPublisher eventPublisher) {
        this.clientRepository = clientRepository;
        this.companyRepository = companyRepository;
        this.eventPublisher = eventPublisher;
    }

    /**
     * Creates a new client.
     *
     * Business logic:
     * 1. Validate company exists
     * 2. Validate client data
     * 3. Validate duplicate tax ID (if business rule applies)
     * 4. Create client entity
     * 5. Save to repository
     * 6. Publish ClientCreated event
     *
     * @param companyId    ID of the company
     * @param businessName Business name of the client
     * @param taxId        Tax ID of the client
     * @param address      Street address
     * @param city         City
     * @param postalCode   Postal code
     * @param province     Province
     * @param country      Country (defaults to "España")
     * @param phone        Phone number
     * @param email        Email of the client
     * @return Created Client entity
     * @throws ResourceNotFoundException if company doesn't exist
     * @throws IllegalArgumentException  if validation fails
     */
    public Client execute(
            Long companyId,
            String businessName,
            String taxId,
            String address,
            String city,
            String postalCode,
            String province,
            String country,
            String phone,
            String email) {
        log.debug("Creating client for company {} with business name: {}", companyId, businessName);

        // Validate company exists
        if (!companyRepository.existsById(companyId)) {
            throw new ResourceNotFoundException("Company not found with id: " + companyId);
        }

        // Validate client data (including address as mandatory for new clients)
        validateClientData(businessName, taxId, address);

        // Validate duplicate tax ID for this company
        if (clientRepository.existsByTaxIdAndCompanyId(taxId, companyId)) {
            throw new IllegalArgumentException("A client with this Tax ID already exists for this company");
        }

        // Create domain entity with all fields
        Client client = new Client(
                null, // ID will be generated by database
                businessName != null ? businessName.trim() : null,
                taxId != null ? taxId.trim() : null,
                address != null ? address.trim() : null,
                city != null ? city.trim() : null,
                postalCode != null ? postalCode.trim() : null,
                province != null ? province.trim() : null,
                country != null ? country.trim() : "España",
                phone != null ? phone.trim() : null,
                email != null ? email.trim() : null,
                companyId);

        // Save to repository
        Client savedClient = clientRepository.save(client);
        log.info("Client created successfully with id: {} for company: {}", savedClient.getId(), companyId);

        // Publish event
        try {
            eventPublisher.publishClientCreated(savedClient);
        } catch (Exception e) {
            // Log but don't fail the transaction - event publishing is best effort
            log.warn("Failed to publish ClientCreated event for client {}", savedClient.getId(), e);
        }

        return savedClient;
    }

    /**
     * Validates client data.
     *
     * @param businessName Business name
     * @param taxId        Tax ID
     * @param address      Address (mandatory for new clients)
     * @throws IllegalArgumentException if validation fails
     */
    private void validateClientData(String businessName, String taxId, String address) {
        if (businessName == null || businessName.trim().isEmpty()) {
            throw new IllegalArgumentException("Business name cannot be empty");
        }

        if (businessName.trim().length() > 255) {
            throw new IllegalArgumentException("Business name cannot exceed 255 characters");
        }

        if (taxId == null || taxId.trim().isEmpty()) {
            throw new IllegalArgumentException("Tax ID cannot be empty");
        }

        if (taxId.trim().length() > 50) {
            throw new IllegalArgumentException("Tax ID cannot exceed 50 characters");
        }

        // Address is mandatory for new clients
        if (address == null || address.trim().isEmpty()) {
            throw new IllegalArgumentException("Address cannot be empty");
        }
    }
}
